version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    networks:
      - shop-network

  grocery-service:
    build: ./grocery-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo-db:27017/grocery_db
    depends_on:
      - mongo-db
    networks:
      - shop-network

  mongo-db:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - shop-network

  cart-service:
    build: ./cart-service
    ports:
      - "5003:5003"
    networks:
      - shop-network

  order-service:
    build: ./order-service
    ports:
      - "5004:5004"
    networks:
      - shop-network

  frontend-service:
    build: ./frontend-service
    ports:
      - "5000:5000"
    environment:
      - AUTH_SERVICE=http://auth-service:5001
      - GROCERY_SERVICE=http://grocery-service:5002
      - CART_SERVICE=http://cart-service:5003
      - ORDER_SERVICE=http://order-service:5004
    depends_on:
      - auth-service
      - grocery-service
      - cart-service
      - order-service
    networks:
      - shop-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - shop-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge
